<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <EnableSourceLink>true</EnableSourceLink>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <RestoreLockedMode>true</RestoreLockedMode>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
    <PublishTrimmed>true</PublishTrimmed>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <!-- Enforce code styling when building in Release mode so devs are not bothered during development in Debug mode -->
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <!-- Disables legacy code analysis as analyzers are included in .NET SDK -->
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <CSharpier_Check>true</CSharpier_Check>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>

    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Meziantou.Analyzer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>
