name: 'Copilot Setup Steps'

on:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: copilot
    steps:
{{ if copilotSetupInstallRipgrep }}
      - shell: bash
        name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
{{ end }}{{ if copilotSetupInstallRtk }}
      - shell: bash
        name: Install RTK
        run: curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/9cc4937dac3ba9aa27147699afe66a2842e7bffc/install.sh | sh
{{ end }}
