using YamlDotNet.Serialization;

namespace Lunapack.Cli;

[YamlStaticContext]
[YamlSerializable(typeof(ProjectManifest))]
[YamlSerializable(typeof(ProjectManifest.LocalSource))]
[YamlSerializable(typeof(ProjectManifest.InstalledPack))]
[YamlSerializable(typeof(ProjectManifest.ManagedFile))]
[YamlSerializable(typeof(PackManifest))]
[YamlSerializable(typeof(PackManifest.PackManagedFile))]
[YamlSerializable(typeof(PackManifest.PackManagedFileStrategy))]
[YamlSerializable(typeof(PackManifest.PackSource))]
[YamlSerializable(typeof(PackManifest.PackParameter))]
[YamlSerializable(typeof(PackManifest.PackScripts))]
[YamlSerializable(typeof(PackManifest.LifecycleScript))]
[YamlSerializable(typeof(PackManifest.PackReference))]
[YamlSerializable(typeof(ProjectConfiguration))]
[YamlSerializable(typeof(ProjectConfiguration.Source))]
[YamlSerializable(typeof(ProjectConfiguration.GitSource))]
[YamlSerializable(typeof(ProjectConfiguration.LocalSource))]
[YamlSerializable(typeof(ProjectConfiguration.ProjectTrust))]
[YamlSerializable(typeof(ProjectConfiguration.Remapping))]
[YamlSerializable(typeof(ProjectConfiguration.RequestedPack))]
[YamlSerializable(typeof(ProjectConfiguration.TrustedPack))]
[YamlSerializable(typeof(ProjectLockFile))]
[YamlSerializable(typeof(ProjectLockFile.ManagedFile))]
[YamlSerializable(typeof(ProjectLockFile.ManagedFileStrategy))]
[YamlSerializable(typeof(ProjectLockFile.PackReference))]
[YamlSerializable(typeof(ProjectLockFile.ResolvedPack))]
[YamlSerializable(typeof(GitSourceProvenance))]
[YamlSerializable(typeof(ProjectLockFile.ExternalSourceLock))]
[YamlSerializable(typeof(ConfiguredSourceIdentity))]
[YamlSerializable(typeof(LocalProjectTrust))]
[YamlSerializable(typeof(TrustedPackIdentity))]
[YamlSerializable(typeof(UserSettings))]
[YamlSerializable(typeof(UserTrust))]
public partial class LunapackYamlContext : StaticContext { }
