<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Lunapack.ToolPackage.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>luna</AssemblyName>
    <AotRuntimeIdentifiers>win-x64;linux-x64;linux-arm64;osx-x64;osx-arm64</AotRuntimeIdentifiers>
    <RuntimeIdentifiers>win-x64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="Scriban" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
