<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Include="..\..\..\..\docs\developer\cli\commands.md" Link="TestData\commands.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\schema\pack.schema.json" Link="TestData\pack.schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\schema\lunapack.schema.json" Link="TestData\lunapack.schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content
      Include="..\..\..\schema\lunapack-lock.schema.json"
      Link="TestData\lunapack-lock.schema.json"
    >
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lunapack.Cli\Lunapack.Cli.csproj" />
  </ItemGroup>
</Project>
