<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Include="..\..\..\..\docs\developer\cli\commands.md" Link="TestData\commands.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lunapack.Cli\Lunapack.Cli.csproj" />
  </ItemGroup>
</Project>
