name: 'PR: CLI'

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - main
    paths:
      - 'projects/cli/**'
      - '.github/actions/cli/**'
      - '.github/workflows/cli.yml'
      - '.github/workflows/cli-pr.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Build Luna CLI
        if:
        uses: ./.github/actions/cli/build
        with:
          runtime-identifier: linux-x64
          publish-artifacts: 'false'
