name: 'PR: Website'

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - main
    paths:
      - 'docs/developer/**'
      - 'projects/website/src/**'
      - '.github/actions/website/**'
      - '.github/workflows/website.yml'
      - '.github/workflows/website-pr.yml'

permissions:
  contents: read

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    name: Build Docusaurus site
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Build website
        uses: ./.github/actions/website/build
